### ISSUE TITLE
suggestion FOR IN LOOP

### ISSUE THREAD

**Issue by tarkonian** [rochus-keller/Micron#3]
A suggestion is to introduce or change the FOR TO BY loop to the FOR IN LOOP. 
In the "new" languages (swift, go, rust, odin, etc...) and in the old one (ADA, c++, c#, pascal, etc..) the FOR IN was introduced.
Given an array A, is easy to use the FOR IN loop:

FOR j in A DO

For a simple loop we have

FOR j in 0..n DO

In the old pascal style (also modula-2 and oberon) we need to use something like

- LOW(A) TO HIGH(A) DO
-  j:=0 TO LEN(A) -1 DO
- FIRST(A) TO LAST(A) DO
- etc..

I can´t see advantage of the FOR TO BY loop over the FOR IN.
In the new modula-2 (R10 and now will be refined and called pim5) they use the new for instead of the traditional. 
In the FAQ of one of the author (http://modula-2.net/m2r10/pmwiki.php?n=Project.FAQ) he wrote:

"**You replaced the FOR TO BY with a FOR IN loop. Why the change?**
The FOR TO BY loop is sufficient for iterating over an ordinal type or an indexed collection such as an array. In this day and age, data structures such as sets, trees and dictionaries take a far more prominent role than back in the day when classic Modula-2 was defined. To iterate over those data structures the FOR TO BY loop is insufficient, a FOR IN loop is required instead.

We did not want to maintain two separate FOR loops, one for ordinal types and another for collections. Instead we designed a FOR IN loop that also accommodates ordinal types and thus replaced the FOR TO BY loop altogether."

You have an opinion about this?

Thank you

**Comment by rochus-keller** [comment]
Thanks. My goal is to be as compatible to Oberon (or Pascal) as possible/reasonable. As far as I understand it, the FOR IN syntax would require a lot of additional syntax constructs and rules. Maybe this could be an extension for Oberon+, but I would first have to evaluate wheter there is indeed sufficient added value. And I would definitely not replace the present FOR TO BY because that would break all existing code and documentation.

**Comment by tarkonian** [comment]
Ok Thanks.
